language: node_js
node_js:
  - '12'

branches:
  only:
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - rvm install 2.5.0

install:
  - npm install
  - gem install jekyll html-proofer

script:
  - npm run build
  - jekyll build -d _site/frasco
  - htmlproofer --url-ignore "/img.shields.io/,/github.com/ixkaito/frasco/generate/" ./_site

sudo: false
